//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Shw.rc
//
#define ID_STATUS_MSGLINE               0
#define ID_STATUS_PROGRESSBAR           0
#define IDP_DELETERECORD                1
#define ID_STATUS_PROGRESSMSG           1
#define ID_STATUS_RECORD_KEY            1
#define IDR_MAINFRAME                   2
#define IDP_MARGINSET                   2
#define ID_STATUS_PRIMARY_KEY           2
#define IDR_SHWTYPE                     3
#define IDP_DELETE_INTERLINEAR_PROC     3
#define ID_STATUS_RECORD_POSITION       3
#define ID_STATUS_PROJECT               4
#define IDD_ABOUTBOX                    100
#define IDW_SHW_STATUS_BAR              101
#define IDD_MKR_General_Page            103
#define IDD_cck                         104
#define IDD_FILTERMAIN                  105
#define IDD_RECORD_INSERT               106
#define IDD_SET                         107
#define IDD_FIL                         108
#define IDD_FILE_IMPORT                 109
#define IDD_KEY                         110
#define IDD_SORTINDEX                   111
#define IDD_FIELD_MKR_EDIT              112
#define IDD_RNGSET_INSERT               113
#define IDD_PROGRESS                    114
#define IDD_FILSET                      116
#define IDD_BROWSEFIELDS                119
#define IDD_SET_PAGE                    121
#define IDD_MULTMATCH                   122
#define IDD_DIALOG1                     123
#define IDD_JUMP                        124
#define IDD_WARN_DOC_IN_PATH            125
#define IDD_VAR                         126
#define IDD_SRTSET_PAGE                 127
#define IDD_LANGENC_OPTIONS_PAGE        128
#define IDD_NOMATCHES                   129
#define IDD_SELECT_DB                   130
#define IDD_JUMPINSERT                  131
#define IDD_SORTEDIT                    133
#define IDD_mkrset_Page                 134
#define IDD_FILTERSELECTION             135
#define IDD_AMBIG                       136
#define IDC_RIGHTARROW                  137
#define IDD_FIND                        138
#define IDD_SELECT_PROCESS              140
#define IDD_PARSE                       141
#define IDD_TRIE                        142
#define IDD_TEMPLATE                    146
#define IDD_NEWDBTYP                    147
#define IDD_TYP_RECMKR                  148
#define IDD_INSERT_RECORD               151
#define IDD_DATABASE_SEARCH             152
#define IDD_ExportedFile                161
#define IDD_SELECT_CCTABLE              162
#define IDD_UPGRADESETTINGS             163
#define IDD_SEARCHPATH                  201
#define IDD_JUMPPATH_PAGE               202
#define IDD_SEARCHPATH_PAGE             203
#define IDD_dbtypset                    210
#define IDD_DBTYP_PROPERTIES            211
#define IDD_DBTYP_OPTIONS_PAGE          212
#define IDD_DBTYP_MARKERS_PAGE          213
#define IDD_DBTYP_FILTERS_PAGE          214
#define IDD_DBTYP_JUMPPATH_PAGE         215
#define IDD_DBTYP_INTERLINEAR_PAGE      216
#define IDD_MDF_Format                  221
#define IDD_MDF_FormatPage              222
#define IDD_MDF_Options                 223
#define IDD_MDF_OptionsPage             224
#define IDD_INTPRC                      231
#define IDD_INTPRC_PAGE                 232
#define IDD_lngset                      240
#define IDD_lng_CasePage                241
#define IDD_lng_SortOrdersPage          243
#define IDD_lng_VariablesPage           244
#define IDD_lng_OptionsPage             245
#define IDD_NEWDATABASE                 251
#define IDD_NEWDB_SELTYPE               252
#define IDD_Jump_Path                   254
#define IDD_NEWDOC                      400
#define IDD_LOOKUP                      401
#define IDD_ExportAsStandardFormat      402
#define IDD_ExportAsRichTextFormat      404
#define IDD_ProjectFileSet              405
#define IDC_RIGHTARROW_MAC              406
#define IDD_fil_MarkerText              409
#define IDD_fil_LangEncText             410
#define IDD_PAGE_SETUP                  411
#define IDD_fil_New                     412
#define IDD_fil_MarkerDate              414
#define IDD_EXPRESS_TEXT                415
#define IDD_EXPRESS_LEXICON             416
#define IDD_MDF                         418
#define IDD_ASK_REPLACE                 419
#define IDD_MKR_opt                     420
#define IDD_MKR_RangeSet_Page           421
#define IDC_CURSOR1                     422
#define IDD_LNG_OPTIONS_ADV             423
#define IDD_Export                      425
#define IDD_SelectFields                426
#define IDD_LOOKFAIL                    427
#define IDD_REARRANGE                   428
#define IDD_GIVENPROC                   429
#define IDD_OPTIONS                     430
#define IDD_CORPUS                      432
#define IDD_FILESLIST                   433
#define IDD_RunBatchFile                434
#define IDD_Build_RangeSet              435
#define IDD_No_Project                  438
#define IDD_MDF_AudienceSetup           439
#define IDD_Last_File                   440
#define IDD_RTF_DocumentPage            441
#define IDD_RTF_SectionPage             443
#define IDD_WORDLST                     444
#define IDD_CONCORDANCE                 445
#define IDD_corset                      446
#define IDD_FILE_HASMOVED               447
#define IDD_ExportProcess               448
#define IDD_ExportRTF                   449
#define IDD_ExportSF                    450
#define IDD_ExportProcesses             451
#define IDD_GENERATE                    452
#define IDD_MDF_Reminder                453
#define IDD_DBTypeNotFound              454
#define IDB_Exclamation                 455
#define IDI_Exclamation                 457
#define IDD_ExportCurrentWindow         458
#define IDD_ConvertNewer                459
#define IDD_ConvertOlder                460
#define IDD_INT_OPTIONS                 461
#define IDI_ICON1                       462
#define IDD_MDF_UpdateOlder             464
#define IDD_FILE_OUTPUT                 465
#define IDD_REPLACE                     466
#define IDD_SELECT_MERGE_DB             467
#define IDD_DBTYP_NUMBERING_PAGE        468
#define IDD_SaveFirstPrompt             469
#define IDD_RENUMBER                    470
#define IDD_NUMBER                      471
#define IDD_Set_Up_Numbering            472
#define IDD_ExportXML                   473
#define IDD_cck_RangeSet                474
#define IDD_cck_Referential             475
#define IDD_DB_DIFF_PATH                476
#define IDD_DB_NOT_OPEN                 477
#define IDD_FIELD_NOT_DEFINED           478
#define IDD_WordFormula                 479
#define IDD_WordFormulas                480
#define IDD_cck_DataDefn                481
#define IDD_MKR_DataProperties_Page     482
#define IDD_SELECTDB_COPY               483
#define IDD_CIRCULAR_REPLACEMENT        484
#define IDD_SELECTDB_MOVE               485
#define IDD_JumpPathMatchingCriteria    486
#define IDD_SELECT_TEXT_BREAK_FIELDS    487
#define IDD_SELECT_FIELDS_TO_CHECK      488
#define IDD_Version                     489
#define IDD_DIALOG_ALAN_TEST            490
#define IDD_AlanTestDlg2                491
#define IDD_AlanTestDlg                 492
#define IDD_AlanAdaptIt                 493
#define IDD_HIDEFIELDS                  494
#define IDC_CURSOR2                     495
#define IDC_fil_edtNote                 1000
#define IDC_WORDS                       1000
#define IDC_CORPUS_WORDS                1000
#define IDC_Export_btnBrowseDOT         1000
#define IDC_jumppath_grpSource          1000
#define IDC_cck_btnSkip                 1000
#define IDC_BOOK                        1001
#define IDC_CORPUS_BOOK                 1001
#define IDC_Export_btnPageSetup         1001
#define IDC_jumppath_lblSourceFields    1001
#define IDC_cck_btnSkipAll              1001
#define IDC_CHAPTER                     1002
#define IDC_CORPUS_CHAPTER              1002
#define IDC_Export_chkAutoOpen          1002
#define IDC_MDF_chkNoMDFReminder        1002
#define IDC_jumppath_edtName            1002
#define IDC_cck_chkCheckRangeSets       1002
#define IDC_fil_btnInsert               1003
#define IDC_VERSE                       1003
#define IDC_CORPUS_VERSE                1003
#define IDC_jumppath_lblTarget          1003
#define IDC_cck_chkCheckDataDefn        1003
#define IDC_fil_btnModify               1004
#define IDC_INPUT                       1004
#define IDC_jumpath_chkRefIntegrity     1004
#define IDC_MKR_MARKER                  1005
#define IDC_fil_btnDelete               1005
#define IDC_DATA                        1005
#define IDC_MKR_FIELD_NAME              1006
#define IDC_fil_btnDeleteAll            1006
#define IDC_PROCESS                     1006
#define IDC_Export_edtDOT               1006
#define IDC_NBRPROC_optUseContents      1006
#define IDC_MKR_LNGSET_COMBO            1007
#define IDC_OUTPUT                      1007
#define IDC_WORDLST_OUTPUT              1007
#define IDC_MDF_btnBrowseEnglishLabelsCct 1007
#define IDC_NBRPROC_optUseText          1007
#define IDC_MKR_cboUnder                1008
#define IDC_UPDATE                      1008
#define IDC_LANGUAGE                    1008
#define IDC_MDF_btnBrowseEnglishDot     1008
#define IDC_NBRPROC_edtUseText          1008
#define IDC_EXIT                        1009
#define IDC_MDF_btnBrowseNationalLabelsCct 1009
#define IDC_MDF_edtEnglishLabelsCct     1010
#define IDC_NBRPROC_edtPunctuation      1010
#define IDC_RECORD_INSERT_KEY           1011
#define IDC_fil_chkMatchWhole           1011
#define IDC_COUNT                       1011
#define IDC_WORDLST_COUNT               1011
#define IDC_MDF_edtEnglishDot           1011
#define IDC_TEMP_STARTNUM               1011
#define IDC_SET_NAME                    1012
#define IDC_REFS                        1012
#define IDC_WORDLST_REFS                1012
#define IDC_MDF_edtNationalLabelsCct    1012
#define IDC_FILSET_CONDITION            1013
#define IDC_WORDMARKER                  1013
#define IDC_MDF_edtNationalDot          1013
#define IDC_nbrproc_btnSelectFields     1013
#define IDC_SET_LIST                    1014
#define IDC_fil_edtName                 1014
#define IDC_COUNTMARKER                 1014
#define IDC_MDF_btnBrowseNationalDot    1014
#define IDC_jump_lboPaths               1014
#define IDC_CLOSE                       1015
#define IDC_REFMARKER                   1015
#define IDC_RTF_edtLeftMargin           1015
#define IDC_FIL_NAME                    1016
#define IDC_fil_cboMatchChars           1016
#define IDC_REFCOUNT                    1016
#define IDC_WORDLST_REFCOUNT            1016
#define IDC_RTF_edtRightMargin          1016
#define IDC_NBRPROC_lboTextBreakMkrs    1016
#define IDC_FIL_CONDITION               1017
#define IDC_RTF_edtGutter               1017
#define IDC_NBRPROC_optCurRecord        1017
#define IDC_SOURCEFILE                  1018
#define IDC_fil_lboChoices              1018
#define IDC_SEARCH                      1018
#define IDC_CONCORD_SEARCH              1018
#define IDC_RTF_chkMirrorMargins        1018
#define IDC_NBRPROC_optWholeDB          1018
#define IDC_IMPORT_DESTFILE             1019
#define IDC_fil_btnFirst                1019
#define IDC_RTF_edtTopMargin            1019
#define IDC_IMPORT_DESCRIPTION          1020
#define IDC_fil_btnLast                 1020
#define IDC_BEFMARKER                   1020
#define IDC_RTF_edtBottomMargin         1020
#define IDC_IMPORT_FILEVIEW             1021
#define IDC_fil_lboElements             1021
#define IDC_TARMARKER                   1021
#define IDC_RTF_cboPaperSize            1021
#define IDC_NBRPROC_edtStartRef         1021
#define IDC_IMPORT_KEYFIELD             1022
#define IDC_fil_lblElement              1022
#define IDC_AFTMARKER                   1022
#define IDC_RTF_edtPaperWidth           1022
#define IDC_NBRPROC_lblStartRef         1022
#define IDC_IMPORT_SORTORD              1023
#define IDC_fil_lblText                 1023
#define IDC_RTF_edtPaperHeight          1023
#define IDC_NBRPROC_lblDBType           1023
#define IDC_fil_optBefore               1025
#define IDC_HELP_BUTTON                 1026
#define IDC_fil_optEqual                1026
#define IDC_RTF_chkOddAndEven           1026
#define IDC_FIL_VARIABLES               1027
#define IDC_fil_optAfter                1027
#define IDC_WHOLE                       1027
#define IDC_CONCORD_WHOLE               1027
#define IDC_RTF_chkFirstPage            1027
#define IDC_fil_edtDate                 1028
#define IDC_START                       1028
#define IDC_CONCORD_START               1028
#define IDC_RTF_edtHeaderToEdge         1028
#define IDC_DLG_NOT                     1029
#define IDC_END                         1029
#define IDC_CONCORD_END                 1029
#define IDC_RTF_edtFooterToEdge         1029
#define IDC_MKR_RANGESET                1030
#define IDC_MIDDLE                      1030
#define IDC_CONCORD_MIDDLE              1030
#define IDC_RTF_edtColumnSpacing        1030
#define IDC_IGNORECASE                  1031
#define IDC_CONCORD_IGNORECASE          1031
#define IDC_CONCORD_MATCHCASE           1031
#define IDC_RTF_chkLineBetweenColumns   1031
#define IDC_HEADER                      1032
#define IDC_RTF_edtNumberOfColumns      1032
#define IDC_CONCORD_ALIGNMATCHED        1032
#define IDC_Export_lboExportProcesses   1033
#define IDC_Export_edtName              1034
#define IDC_Export_edtCCT               1035
#define IDC_Export_btnBrowseCCT         1036
#define IDC_Export_edtStylesheet        1037
#define IDC_Export_btnBrowseOutputFile  1037
#define IDC_Export_btnBrowseStylesheet  1038
#define IDC_Export_edtOutputFile        1038
#define IDC_Export_edtOutputFile2       1039
#define chx1                            0x0410
#define IDC_Export_optDocumentTemplate  1040
#define IDC_Export_btnBrowseOutputFile2 1040
#define IDC_Export_optMarkerFont        1041
#define IDC_MDF_lblToPrint              1044
#define IDC_prj_lblFileName             1049
#define IDC_prj_lblName                 1050
#define IDC_MKRSET_MARKER               1051
#define IDC_prj_lblVersion              1051
#define IDC_MKRSET_FIELD_NAME           1052
#define IDC_prj_lboSettingsFiles        1052
#define IDC_MKRSET_LANGUAGE             1053
#define IDC_prj_lblSettingsFolder       1053
#define IDC_prj_lblProjectFile          1054
#define IDC_prj_lblShoeboxVersion       1055
#define IDC_Export_optWithoutReordering 1056
#define IDC_FIELD_MARKER_EDIT           1057
#define IDC_Export_lblPriKeyMarker      1058
#define IDC_MKRSET_RANGESET             1059
#define IDC_Export_lblOtherFields       1059
#define IDC_RNGSET_LIST                 1061
#define IDC_cck_edtInconsistency        1062
#define IDC_cck_btnAdd                  1064
#define IDC_cck_btnReplace              1065
#define IDC_cck_btnReplaceAll           1066
#define IDC_cck_edtReplacement          1071
#define IDC_MKR_VISIBLE                 1072
#define IDC_cck_lboRangeSet             1072
#define IDC_PROGRESS_BAR                1073
#define IDC_cck_lblMarker               1073
#define IDC_PROGRESS_MSG                1074
#define IDC_FIELD_MARKER_COMBO          1076
#define IDC_cck_lblDatabase             1077
#define IDC_cck_lblFilter               1078
#define IDC_cck_lblDatabaseType         1079
#define IDC_USEDEFAULTFONT              1080
#define IDC_cck_chkCheckJumpPaths       1080
#define IDC_cck_optAllFields            1081
#define IDC_cck_optSingleField          1082
#define IDC_cck_cboSingleField          1083
#define IDC_BROWSEFIELDS_GRP            1084
#define IDC_cck_optSelectedFields       1084
#define IDC_BROWSEFIELDS_LBLAVAILABLE   1085
#define IDC_BROWSEFIELDS_LBLTOBROWSE    1086
#define IDC_BROWSEFIELDS_LSTFLDSAVAILABLE 1087
#define IDC_BROWSEFIELDS_LSTFLDSTOBROWSE 1088
#define stc1                            0x0440
#define IDC_BROWSEFIELDS_FIRSTTO        1089
#define stc2                            0x0441
#define IDC_BROWSEFIELDS_LASTTO         1090
#define stc3                            0x0442
#define IDC_BROWSEFIELDS_MOVETO         1091
#define stc4                            0x0443
#define IDC_BROWSEFIELDS_MOVEFROM       1092
#define IDC_BROWSEFIELDS_CLEARBROWSE    1093
#define IDC_DATESTAMP_COMBO             1094
#define IDC_TYP_cboMkrRef               1094
#define IDC_TYP_cboMkrTxt               1095
#define IDC_TEXTREF_COMBO               1095
#define IDC_DS_FLD                      1096
#define IDC_TYP_lblMkrRef               1096
#define IDC_TYP_lblMkrTxt               1097
#define IDC_DS_FLD2                     1097
#define IDC_INTPRC_FROM                 1100
#define IDC_INTPRC_PROC                 1101
#define IDC_STATIC_ADDITIONAL_FIELD     1103
#define IDC_FIELDTOSEARCH2              1106
#define IDC_jumppath_lblTargetFields    1106
#define IDC_jumppath_lblAvailableFields 1107
#define IDC_JUMP_KEY                    1110
#define IDC_JUMPKEY_LABEL               1111
#define IDC_JUMPPATH                    1112
#define IDC_LANGSET_COMBO               1113
#define IDC_LANGENC_LABEL               1114
#define IDC_WARN_DOC_CLOSE              1115
#define IDC_jmp_lblPriJumpPath          1115
#define IDC_jmp_cboPriJumpPath          1116
#define IDC_BACKSLASH_LABEL             1117
#define IDC_SET_FILE_NAME               1119
#define IDC_SET_CHARS                   1120
#define lst1                            0x0460
#define IDC_VAR_NAME                    1121
#define lst2                            0x0461
#define IDC_VAR_CHARS                   1122
#define IDC_MKR_LNG                     1124
#define IDC_SET_DESCRIPTION             1125
#define IDC_srtset_cbosrtDefault        1126
#define IDC_LANGENC_FONT                1127
#define IDC_COPY                        1128
#define IDC_lng_edtName                 1130
#define IDC_lng_edtDescription          1131
#define IDC_kbd_cboKeyboard             1132
#define IDC_TRYAGAIN                    1136
#define cmb1                            0x0470
#define IDC_INSERT                      1137
#define cmb2                            0x0471
#define IDC_NOMATCHES_MSG               1139
#define IDC_NOMATCHES_KEY               1140
#define IDC_SELECTDB_SHOWPATH           1141
#define IDC_SELECTDB_LISTBOX            1142
#define edt1                            0x0480
#define IDC_NOWORDWRAP                  1155
#define IDC_chkNoWordWrap               1155
#define IDC_mkrset_cbolngDefault        1167
#define IDC_mkrset_lblMarker            1168
#define IDC_mkrset_lblFieldName         1169
#define IDC_mkrset_lblLanguage          1170
#define IDC_mkrset_lblUnder             1171
#define IDC_FILSEL_FILTERS              1173
#define IDC_AMBIG_LIST                  1176
#define IDC_AMBIG_WORD                  1177
#define IDC_FIND_TEXT                   1178
#define IDC_FIND_IN_LNG                 1179
#define IDC_FIND_IN_FLD                 1180
#define IDC_REPLACE_TEXT                1181
#define IDC_FIND_LNGCOMBO               1183
#define IDC_FIND_MKRCOMBO               1184
#define IDC_FIND_CURRENTREC             1186
#define IDC_FIND_ALLRECORDS             1187
#define IDC_FIND_WHOLE_WORD             1188
#define IDC_FIND_MATCH_SAME_PRIMARY     1190
#define IDC_FIND_MATCH_EXACT_DISREGARD_CASE 1191
#define IDC_FIND_MATCH_EXACT            1192
#define IDC_FIND_MATCH_EVEN_IGNORE      1193
#define IDC_INTPRC_TO                   1194
#define IDC_INTPRC_LIST                 1195
#define IDC_SELECT_PROC_LIST            1196
#define IDC_TO_MARKER                   1197
#define IDC_FROM_MARKER                 1199
#define IDC_COMBO2                      1200
#define IDC_fil_cboVariable             1200
#define IDC_PS_MARKER                   1200
#define IDC_PARSE                       1201
#define IDC_PUNC_MARKER                 1201
#define IDC_FORCE_GLOSS_START           1202
#define IDC_ROOT                        1203
#define IDC_PREFIX                      1204
#define IDC_SUFFIXES                    1205
#define IDC_INFIXES                     1206
#define IDC_FORCE_GLOSS_END             1207
#define IDC_MORPHEME_BOUND              1208
#define IDC_INTPRC_DESCRIPTION          1211
#define IDC_COMBO1                      1212
#define IDC_fil_cboMarker               1212
#define IDC_MDF_cboFilter               1212
#define IDC_LANGENC                     1212
#define IDC_FILESLIST_DRIVE             1212
#define IDC_CONCORD_CORPUS              1212
#define IDC_CORPUS_LANGENC              1212
#define IDC_TYP_RECMKR                  1213
#define IDC_IMPORT_DBTYP                1214
#define IDC_lng_edtCase                 1220
#define IDC_lng_edtPunct                1221
#define IDC_lng_lblChar                 1222
#define IDC_lng_lblOtherCase            1223
#define IDC_lng_lblStandardChar         1224
#define IDC_lng_lblHex                  1226
#define IDC_lng_lblDec                  1227
#define IDC_JUMP_WHOLE_KEY              1228
#define IDC_JUMP_MATCH_SAME_PRIMARY     1229
#define IDC_JUMP_MATCH_EXACT_DISREGARD_CASE 1230
#define IDC_JUMP_MATCH_EXACT            1231
#define IDC_JUMP_MATCH_EVEN_IGNORE      1232
#define IDC_INCLUDE_CONTENTS            1233
#define IDC_DATABASE_TYPES              1238
#define IDC_BROWSE_CCTABLE              1239
#define IDC_BACKUP_ORI                  1240
#define IDC_USE_CCTABLE                 1241
#define IDC_LBL_CCTABLE                 1242
#define IDC_BROWSE                      1243
#define IDC_WORDLST_BROWSE              1243
#define IDC_FILTERMAIN_CHKUSEFILTER     1301
#define IDC_FILTERMAIN_CBXSELECT        1302
#define IDC_FILTERMAIN_EDITFILTERS      1303
#define IDC_KEY_LABEL                   1321
#define IDC_KEY_NAME                    1322
#define IDC_KEY_KEY                     1324
#define IDC_KEY_WHOLE_KEY               1325
#define IDC_KEY_MATCH_SAME_PRIMARY      1326
#define IDC_KEY_MATCH_EXACT_DISREGARD_CASE 1327
#define IDC_KEY_MATCH_EXACT             1328
#define IDC_KEY_MATCH_EVEN_IGNORE       1329
#define IDC_SORTINDEX_LSTMRKSAVAILABLE  1351
#define IDC_SORTINDEX_LSTMRKSTOSORT     1352
#define IDC_SORTINDEX_MOVETO            1353
#define IDC_SORTINDEX_MOVEFROM          1354
#define IDC_SORTINDEX_LBLAVAILABLE      1356
#define IDC_SORTINDEX_LBLTOSORT         1357
#define IDC_SORTINDEX_CBXFIRSTFLD_SO    1358
#define IDC_SORTINDEX_LBLFIRSTFIELDSORTORD 1359
#define IDC_SORTINDEX_CHKSORTFROMEND    1360
#define IDC_SORTINDEX_LBLSORTFROMEND    1361
#define IDC_SORTINDEX_LBLSORTFROMEND1   1362
#define IDC_SORTINDEX_FIRSTTO           1364
#define IDC_SORTINDEX_LASTTO            1366
#define IDC_SORTINDEX_CLEARSORTS        1367
#define IDC_SORTINDEX_LBLSORTFROMEND2   1368
#define IDC_SORTINDEX_FLDSGROUP         1369
#define IDC_NEW                         1381
#define IDC_ADD                         1382
#define IDC_MODIFY                      1383
#define IDC_DELETE                      1384
#define IDC_APPLY                       1385
#define IDC_RANGESET                    1386
#define IDC_MKRFONT                     1387
#define IDC_USE                         1388
#define IDC_SEARCHPATH_LBLAVAILABLE     1401
#define IDC_jumppath_lblAvailable       1401
#define IDC_SEARCHPATH_LBLINPATH        1402
#define IDC_jumppath_lblDBsInPath       1402
#define IDC_SEARCHPATH_LSTDBSAVAILABLE  1403
#define IDC_jumppath_lboDBsAvailable    1403
#define IDC_SEARCHPATH_LSTPATH          1404
#define IDC_jumppath_lboPaths           1404
#define IDC_SEARCHPATH_FIRSTTO          1405
#define IDC_jumppath_btnFirst           1405
#define IDC_SEARCHPATH_LSTDBSAVAILABLE2 1406
#define IDC_SEARCHPATH_LASTTO           1407
#define IDC_jumppath_btnLast            1407
#define IDC_SEARCHPATH_LSTPATH2         1408
#define IDC_SEARCHPATH_MOVETO           1409
#define IDC_jumppath_btnInsert          1409
#define IDC_SEARCHPATH_MOVEFROM         1410
#define IDC_jumppath_btnRemovePath      1410
#define IDC_SEARCHPATH_REMOVE           1411
#define IDC_SEARCHPATH_CLEAR            1412
#define IDC_jumppath_btnClearPaths      1412
#define IDC_SEARCHPATH_MOVETO2          1413
#define IDC_SEARCHPATH_REMOVE2          1414
#define IDC_SEARCHPATH_LBLAVAILABLE2    1415
#define IDC_SEARCHPATH_LBLINPATH2       1416
#define IDC_SEARCHPATH_FIELDTOSEARCH    1417
#define IDC_jumppath_lblFieldToSearch   1417
#define IDC_SEARCHPATH_MKR_COMBO        1418
#define IDC_jumppath_cboTargetFields    1418
#define IDC_SEARCHPATH_OPEN             1419
#define IDC_SEARCHPATH                  1420
#define IDC_SEARCHPATH_WARNDOCCLOSE     1421
#define IDC_jumppath_chkWarnDocClose    1421
#define IDC_SEARCHPATH_SHOWPATH         1422
#define IDC_jumppath_chkShowPath        1422
#define IDC_MULTMATCH_MESSAGE           1451
#define IDC_MULTMATCH_LIST              1452
#define IDC_MULTMATCH_WORD              1453
#define IDC_MULTMATCH_DATABASE          1454
#define IDC_MULTMATCH_ADDITIONAL_FIELD  1455
#define IDC_MULTMATCH_ADDITIONAL_FIELD1 1456
#define IDC_MULTMATCH_MKRS              1457
#define IDC_MULTMATCH_ADDITIONAL_FIELD2 1458
#define IDC_MULTMATCH_SHOWPATH          1459
#define IDC_MDF_btnEnglishDictionary    1471
#define IDC_MDF_btnNationalDictionary   1472
#define IDC_MDF_btnEnglishFinderlist    1473
#define IDC_MDF_btnNationalFinderlist   1474
#define IDC_MDF_edtEnglishDictionary    1475
#define IDC_MDF_edtNationalDictionary   1476
#define IDC_MDF_edtEnglishFinderlist    1477
#define IDC_MDF_edtNationalFinderlist   1478
#define IDC_MDF_chkDoubleColumn         1479
#define IDC_MDF_chkDiglot               1480
#define IDC_MDF_chkHeader               1480
#define IDC_MDF_chkSortByCitationForm   1481
#define IDC_MDF_chkIncludeKey           1482
#define IDC_MDF_chkIncludeLexemeWithCitation 1482
#define IDC_MDF_chkIncludeLexemeWithCitationForm 1482
#define IDC_MDF_chkIncludeExamples      1483
#define IDC_MDF_chkIncludeNotes         1484
#define IDC_MDF_chkIncludePartOfSpeech  1485
#define IDC_MDF_chkNewHierarchy         1486
#define IDC_MDF_optDiglot               1487
#define IDC_MDF_optTriglot              1488
#define IDC_SORTEDIT_SECONDSAFTER       1501
#define IDC_SORTEDIT_SECONDSBEFORE      1502
#define IDC_SORTEDIT_PRIMARIES          1503
#define IDC_SORTEDIT_IGNORES            1504
#define IDC_SORTEDIT_CHKSPACEPRECEDES   1505
#define IDC_SORTEDIT_CHKSECONDARIESAFTER 1506
#define IDC_SORTEDIT_NAME               1507
#define IDC_SORTEDIT_DESCRIBE           1508
#define IDC_TRIE_LSTMKRSAVAILABLE       1521
#define IDC_TRIE_LSTMKRSTOFIND          1522
#define IDC_TRIE_MKRMOVETO              1523
#define IDC_TRIE_MKRREMOVE              1524
#define IDC_TRIE_MKROUTPUT              1525
#define IDC_TRIE_LSTDBSAVAILABLE        1526
#define IDC_TRIE_LSTDBSTOSEARCH         1527
#define IDC_TRIE_MOVETO                 1528
#define IDC_TRIE_REMOVE                 1529
#define IDC_TRIE_LBLDBSRCH              1530
#define IDC_TRIE_LBLAVAILABLE           1531
#define IDC_TRIE_SHOWPATH               1532
#define IDD_CrashFixFilePathEdit        1537
#define IDD_ImportFileDBTyp             1538
#define IDC_TYP_EDITDESCRIPTION         1542
#define IDC_TYP_RECORDMKR_COMBO         1543
#define IDC_TYP_NAME                    1544
#define IDC_TYP_RECORDMARKER            1545
#define IDC_TYP_NAME_EDIT               1546
#define IDC_EDIT_FC_GLOSS_ST            1561
#define IDC_EDIT_FC_GLOSS_ST2           1562
#define IDC_OUTPUT_MARKER               1563
#define IDC_EDIT_FC_GLOSS_END           1564
#define IDC_EDIT_FC_GLOSS_ST3           1565
#define IDC_EDIT_MORPH_BOUND            1566
#define IDC_EDIT_MORPH_BREAKS           1567
#define IDC_NEWDOC_DBTYP                1600
#define IDC_LBL_FILENAME                1601
#define IDC_TYP_INTERLINEAR_SPACING     1602
#define IDC_EDIT_INTERLINEAR_SPACING    1602
#define IDC_PARSE_AFFIXES_IN_LEX        1603
#define IDC_PARSE_PARSES_IN_LEX         1604
#define IDC_LOOKUP                      1605
#define IDC_mkr_optCharStyle            1606
#define IDC_mkr_optParStyle             1607
#define IDC_mkrset_lblMisc              1607
#define IDC_Export_optEntireDatabase    1609
#define IDC_Export_optCurrentWindow     1610
#define IDC_Export_optCurrentRecord     1611
#define IDC_Export_lblFiltering         1612
#define IDC_Export_lblSorting           1613
#define IDC_rtf_optAllFieldsToPars      1614
#define IDC_rtf_optAllRecordsToPars     1615
#define IDC_rtf_optMarkerStyle          1616
#define IDC_rtf_chkIncludeMarkers       1617
#define IDC_rtf_chkIncludeFormatting    1619
#define IDC_SHOW_FAIL_MARK              1623
#define IDC_SHOW_WORD                   1624
#define IDC_APPLYCC                     1625
#define IDC_SH2_PARSE                   1626
#define IDC_SHOW_ROOT                   1628
#define IDC_Project_lblDir              1629
#define IDC_FILTER_LIST                 1630
#define IDC_KEEPCAP                     1631
#define IDC_KEEPPUNC                    1632
#define IDC_fil_edtText                 1633
#define IDC_fil_btnInsertVariable       1634
#define IDC_fil_cboLangEnc              1635
#define IDC_STOP_AT_SEMICOLON           1636
#define IDC_PAGESETUP_TXT_HEADER        1637
#define IDC_PAGESETUP_TXT_FOOTER        1638
#define IDC_PAGESETUP_TXT_MARGLEFT      1639
#define IDC_PAGESETUP_TXT_MARGRIGHT     1640
#define IDC_PAGESETUP_TXT_MARGTOP       1641
#define IDC_PAGESETUP_TXT_MARGBOTTOM    1642
#define IDC_PAGESETUP_RB_PRINTVIEW      1643
#define IDC_PAGESETUP_RB_PRINTREC       1644
#define IDC_PAGESETUP_CHK_PAGEBREAKS    1645
#define IDC_Import_chkRemoveSpaces      1648
#define IDC_EXPRESS_SETUP               1650
#define IDC_LSTDBSAVAILABLE             1659
#define IDC_LSTDBSTOSEARCH              1660
#define IDC_MOVETO                      1661
#define IDC_REMOVE                      1662
#define IDC_ALT                         1664
#define IDC_UND                         1665
#define IDC_TEXT                        1667
#define IDC_MB                          1668
#define IDC_GLOSS                       1669
#define IDC_PS                          1670
#define IDC_EDIT_GLOSS_SEPARATOR        1671
#define IDC_MDF_chkAlternateHierarchy   1676
#define IDC_MDF_btnOptions              1680
#define IDC_MDF_edtTitle                1682
#define IDC_REPLACE_ALL                 1690
#define IDC_SKIP                        1691
#define IDC_MKR_OPTIONS_PLAYSOUND       1692
#define IDC_MKR_DESCRIPTION             1693
#define IDC_MKR_BTNRANGESET             1694
#define IDC_btnDataProperties           1694
#define IDC_LNG_RIGHTTOLEFT             1695
#define IDC_LNG_DLLNAME                 1696
#define IDC_LNG_DLLTABLE                1697
#define IDC_BUTTON_LNG_ADV              1697
#define IDC_rtf_chkAutoOpen             1698
#define IDC_Export_chkAllFields         1699
#define IDC_Export_btnSelectFields      1700
#define IDC_MDF_btnSelectFields         1703
#define IDC_MDF_optEnglish              1704
#define IDC_MDF_optNational             1705
#define IDC_MDF_optFinderlist           1708
#define IDC_MDF_optEnglishGlossIndex    1708
#define IDC_MDF_chkAutoOpen             1709
#define IDC_Export_optSF                1711
#define IDC_Export_optRTF               1712
#define IDC_Export_optMDF               1713
#define IDC_mrfset_lboExcluded          1715
#define IDC_jumppath_lboAvailableFields 1715
#define IDC_mrfset_btnAdd               1716
#define IDC_jumppath_btnAddField        1716
#define IDC_mrfset_btnRemove            1717
#define IDC_jumppath_btnRemoveField     1717
#define IDC_mrfset_lboIncluded          1718
#define IDC_jumppath_lboSourceFields    1718
#define IDC_TYP_chkMDF                  1719
#define IDC_TYP_chkDisableNumbering     1719
#define IDC_InsertFail                  1723
#define IDC_InfixBefore                 1725
#define IDC_Adapt                       1726
#define IDC_LBL_RULEFILE                1727
#define IDC_InfixMultiple               1727
#define IDC_BROWSE_RULEFILE             1728
#define IDC_TOOLBAR                     1729
#define IDC_STATUSBAR                   1730
#define IDC_LARGECTRLS                  1731
#define IDC_MARKERFONT                  1732
#define IDC_MDF_chkIncludeNonMDF        1734
#define IDC_MDF_chkDate                 1735
#define IDC_MDF_lblHierarchy            1736
#define IDC_UNLIMITED                   1745
#define IDC_WORDLST_UNLIMITED           1745
#define IDC_MATCHCOUNT                  1746
#define IDC_CONCORD_MATCHCOUNT          1746
#define IDC_LIMITED                     1747
#define IDC_WORDLST_LIMITED             1747
#define IDC_NAME                        1748
#define IDC_CORPUS_NAME                 1748
#define IDC_FILESLIST                   1749
#define IDC_CORPUS_FILESLIST            1749
#define IDC_FILESLIST_FIRSTTO           1752
#define IDC_FILESLIST_LSTAVAILABLE      1754
#define IDC_FILESLIST_LSTSELECTED       1755
#define IDC_FILESLIST_LASTTO            1756
#define IDC_FILESLIST_MOVETO            1757
#define IDC_FILESLIST_MOVEFROM          1758
#define IDC_FILESLIST_CLEAR             1759
#define IDC_FILESLIST_SHOWPATH          1760
#define IDC_FILESLIST_PATH              1761
#define IDC_FILESLIST_LSTPATH           1762
#define IDC_CONCORD_CORPUS_EDIT         1763
#define IDC_CONCORD_UNLIMITED           1764
#define IDC_CONCORD_LIMITED             1765
#define IDC_CONCORD_OUTPUT              1766
#define IDC_CONCORD_BROWSE              1767
#define IDC_WORDLST_CORPUS              1768
#define IDC_WORDLST_CORPUS_EDIT         1769
#define ID_RUNDOS                       1770
#define IDC_STATUS                      1771
#define IDC_FILESLIST_UPDIR             1772
#define IDC_CONCORD_CURDIR              1773
#define IDC_WORDLST_CURDIR              1774
#define IDC_CORPUS_EDITLANGENC          1775
#define IDC_Version                     1776
#define IDC_MRK_RANGESET_CONDITION      1777
#define IDC_MKR_RANGESET_CONDITION      1777
#define IDC_MKR_RANGESET_WholeWords     1777
#define IDC_RADIO2                      1778
#define DC_MKR_RANGESET_SPACE           1779
#define IDC_MKR_RANGESET_SPACE          1779
#define IDC_MKR_RANGESET_MESSAGE        1780
#define IDC_Marker_Combo                1781
#define ID_MODIFY                       1783
#define IDC_No_Project_Selection        1785
#define IDC_RADIO3                      1786
#define IDC_MDF_chkIncludeRegionalWithNational 1787
#define IDC_MDF_chkTotal                1788
#define IDC_MDF_btnAudience             1789
#define IDC_Yes                         1790
#define IDC_No                          1791
#define IDC_MKR_cboFollowing            1793
#define IDC_NBRPROC_edtUseContents      1793
#define IDC_NBRPROC_cboUseContents      1793
#define IDC_RTF_lblLeftInside           1794
#define IDC_RTF_lblRightOutside         1795
#define IDC_RTF_lblMeasurementUnit      1796
#define IDC_MDF_btnPageSetup            1797
#define IDC_RTF_btnPageSetup            1798
#define IDC_RangeSetField               1800
#define ID_BuildRangeSet                1801
#define IDC_Rangeset_Messagefield       1802
#define IDC_Rangeset_Message            1803
#define IDC_MKR_RANGESET_Characters     1804
#define IDC_BrowseEmptyField            1805
#define IDC_MKR_RANGESET_SPACE2         1805
#define IDC_BrowseNoField               1806
#define IDC_Export_lblType              1811
#define IDC_Export_btnProcesses         1812
#define IDC_SET_LABEL                   1813
#define IDC_mrfset_chkAutoInclude       1814
#define IDC_Export_lblEntireDatabase    1816
#define IDC_KeepMBrks                   1817
#define IDC_CompRoot                    1818
#define IDC_PreferPrefix                1820
#define IDC_PreferSuffix                1821
#define IDC_BalanceAffixes              1822
#define IDC_DBTypeNF_FileAndType        1826
#define IDC_lblWhyImport                1827
#define IDC_Import_CCGroup              1828
#define IDC_Export_chkShowProperties    1829
#define IDC_MDF_btnAudienceSetup        1834
#define IDC_PAGESETUP_CHK_PAGEBREAKS2   1835
#define IDC_NOWORDWRAP2                 1836
#define IDC_RequireMatch                1837
#define IDC_UseWordFormulas             1837
#define IDC_MDF_optWebPages             1839
#define IDC_Export_optMDF_HTML          1840
#define IDC_Export_optXML               1840
#define IDC_MDF_optNationalGlossIndex   1841
#define IDC_MDF_optRegionalGlossIndex   1842
#define IDC_MDF_lblMarkerHierarchy      1843
#define IDC_MDF_edtCopyright            1844
#define IDC_Export_lblDatabaseType      1845
#define IDC_RTF_chkInterlinearTabAligned 1846
#define IDC_RTF_lblInterlinearSpacing   1847
#define IDC_RTF_edtInterlinearSpacing   1848
#define IDC_MDF_optDocument             1849
#define IDC_mrfset_btnRemoveAll         1850
#define IDC_jumppath_btnClearFields     1850
#define IDC_mrfset_lblInstructions      1851
#define IDC_NBRPROC_lblMkrRef           1852
#define IDC_NBRPROC_lblMkrTxt           1853
#define IDC_MDF_lblShoeboxVersion       1854
#define IDC_MDF_lblProjectSettings      1855
#define IDC_MDF_lblNewerMDF             1856
#define IDC_MDF_lblDefaultSettings      1857
#define IDC_jumppath_chkDefault         1859
#define IDC_Export_chkCheckConsistency  1860
#define IDC_Export_chkOverwrite         1861
#define IDC_cck_btnModify               1862
#define IDC_Export_chkAddAlphDiv        1862
#define IDC_cck_btnInsert               1864
#define IDC_cck_lblWhiteSpace           1865
#define IDC_cck_lblInconsistency        1866
#define IDC_NBRPROC_lblDBName           1867
#define IDC_NBRPROC_edtCurRecord        1868
#define IDC_lblOpenDB                   1873
#define ID_FIX_IT                       1876
#define ID_SKIP                         1877
#define IDC_lblJumpPath                 1878
#define IDC_lblClosedDB                 1879
#define IDC_lblDB                       1880
#define IDC_lblMkr                      1881
#define IDC_cck_edtFailedData           1886
#define IDC_wdf_lblSymbol               1887
#define IDC_wdf_lblRules                1888
#define IDC_wdf_lblPatterns             1888
#define IDC_wdf_cboLangEncRules         1889
#define IDC_wdf_cboLangEncPatterns      1889
#define IDC_wdf_edtSymbol               1890
#define IDC_wdf_chkPrimarySymbol        1891
#define IDC_wdf_edtRules                1892
#define IDC_wdf_edtPatterns             1892
#define IDC_wdf_chkEnableWordFormulas   1893
#define IDC_wdf_btnFormulas             1894
#define IDC_CLEAR                       1895
#define IDC_cck_btnSelectFields         1896
#define IDC_wdf_chkShowExpandedList     1897
#define IDC_kbd_lblKeyboard             1898
#define IDC_kbd_chkAutoSwitching        1899
#define IDC_wdf_lblEtc                  1900
#define IDC_wdf_btnPrimary              1901
#define IDC_btnVersionInfo              1902
#define IDC_chkUseRangeSet              1903
#define IDC_btnRangeSet                 1904
#define IDC_chkAllowEmptyContents       1905
#define IDC_optSingleWord               1906
#define IDC_lstRangeSet                 1907
#define IDC_lboRangeSet                 1908
#define IDC_edtElement                  1909
#define IDC_btnAdd                      1910
#define IDC_btnReplace                  1911
#define IDC_btnDelete                   1912
#define IDC_btnClear                    1913
#define IDC_btnBuildRangeSet            1914
#define IDC_optMultipleWords            1915
#define IDC_btnConvertCharRangeSet      1916
#define IDC_optSingleItem               1917
#define IDC_btnMoreInfo                 1918
#define IDC_lblCharRangeSet             1919
#define IDC_lblSelectDB                 1920
#define IDC_edtFrom1                    1921
#define IDC_edtTo1                      1922
#define IDC_edtFrom2                    1923
#define IDC_edtTo2                      1924
#define IDC_jumppath_Matching           1925
#define IDC_DIR_SELECT                  1926
#define IDC_LNG_UNICODE                 1928
#define IDC_NOMATCHES_KEYU              1930
#define IDC_LIST2                       1936
#define IDC_LIST1                       1937
#define IDC_CUSTOM2                     1940
#define IDC_EDIT1                       1942
#define IDC_Primary                     1943
#define IDC_LBL_KeymanFile              1946
#define IDC_Browse_KeymanFile           1947
#define IDC_LBL_SortCCTable             1948
#define IDC_LookupFailureKey            1948
#define IDC_WholeWord                   1949
#define IDC_Export_chkHideFields        1949
#define IDC_Export_edtChainProcess      1950
#define IDC_CalcCorr                    1951
#define IDC_CollectCorr                 1952
#define IDC_HIDEFIELDS_LBLTOHIDE        1953
#define IDC_HIDEFIELDS_LBLAVAILABLE     1954
#define IDC_HIDEFIELDS_GRP              1955
#define IDC_HIDEFIELDS_LSTFLDSAVAILABLE 1956
#define IDC_HIDEFIELDS_LSTFLDSTOHIDE    1957
#define IDC_HIDEFIELDS_FIRSTTO          1958
#define IDC_HIDEFIELDS_LASTTO           1959
#define IDC_HIDEFIELDS_MOVETO           1960
#define IDC_HIDEFIELDS_MOVEFROM         1961
#define IDC_HIDEFIELDS_CLEARHIDE        1962
#define IDC_LongerOverride              1963
#define IDC_OverrideShowAll             1965
#define IDC_EDIT_Name                   1967
#define IDC_EDIT_iSuccPercent           1968
#define IDC_EDIT_iTestSequenceNumber    1969
#define IDC_EDIT_Comment                1970
#define IDC_MDF_edtChainProcess         1971
#define IDC_UseInternalKeyboard         1972
#define IDC_Copyright                   1973
#define IDS_FILSET_TITLE                61264
#define IDS_MKRSET_TITLE                61266
#define IDS_VARSET_TITLE                61287
#define IDS_SRTSET_TITLE                61289
#define IDS_JMPSET_TITLE                62342
#define IDS_DELETE_INTERLIN_PROC        62343
#define IDC_jumppath_grpTarget          -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        496
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1973
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
